apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudbuilders-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cloudbuilders.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudbuilders-svc   
                port:
                  number: 80
